spring:
    datasource:
        driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
        url: jdbc:cubrid:localhost:33000:demodb:public::?charSet=utf-8
        username: dba

    jpa:
        database-platform: org.hibernate.dialect.CUBRIDDialect

